### ISSUE TITLE
「Google XML Sitemaps」プラグインでsitemap.xmlを作るとForbidden

### ISSUE THREAD

**Issue by noblejasper** [becyn/fluxflex_wordpress_3.2.1#2]
「Google XML Sitemaps」プラグインを入れて、
sitemap.xmlを作成して、/sitemap.xmlにアクセスしてみるとForbiddenになってしまいます。

ちょっと問題点がわからなかったので、こちらに書かせていただきました。
確認＆対応お願いします。

fluxflexのページにも書き込みしておきます。

**Comment by becyn** [comment]
noblejasper さん

ありがとうございます。
少しこちらでも調べさていただきます。
また何か分かり次第、こちらにてご報告させていただきます。

**Comment by noblejasper** [comment]
ありがとうございます！

とりあえず僕も調べてはみます。。。汗
